### ISSUE TITLE
Build out DB using Express w/ Knex & Postgres

### ISSUE THREAD

**Issue by sljohnson32** [sljohnson32/school-finder#38]
Transition Firebase DB to Express w/ Knex and Postgres

**Comment by sljohnson32** [comment]
@danalvarez5280 @jbexx as suggested by Robbie today, I'm building out the API for the application as a separate repo so it can be used as a stand alone API as well.  Just FYI for now.  Am going to share with you in Github shortly.

https://github.com/sljohnson32/CDoE_data_api

**Comment by jbexx** [comment]
Thats a great idea.  That was a big problem I had hosting that code challenge on heroic, it all being in the same repo
