### ISSUE TITLE
Add 'Comparison' component for d3 visualization

### ISSUE THREAD

**Issue by sljohnson32** [sljohnson32/school-finder#49]
The Component should overlay over 98% of the page (with small boarder of map around and title showing) and allow the user to compare 2 (or 3?) schools based on the selected metrics they want to look at.

Slide in and out should act similar to filter animation.

Button to see comparison data should be dynamic based on whether or not schools have been selected to compare.

**Comment by danalvarez5280** [comment]
We will make the d3 graphs their own component, per graph. Will need a favorite button for each school being compared, will need a conditional render of whether or not the school has been favorited.

**Comment by danalvarez5280** [comment]
Add school card component.
